english_grammar/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from home.views import home
from authentication.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
# api schema
from rest_framework.schemas import get_schema_view
# swagger 
from rest_framework_swagger.views import get_swagger_view
# from django.conf.urls import url

# errr handle pages
from authentication.views import page_404
from django.views.static import serve
from home.views import blog




urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('register/', include('authentication.urls')),
    path('', home),
    path('about/', about, name='about'),
    path('edit-profile/<int:id>/', profile_edit, name='profile-edit'),
    path('courses/', Courses, name='courses'),
    path('our-courses/', include('home.urls')),
    path('captcha/', include('captcha.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger-ui/',TemplateView.as_view(template_name="templates/home/swagger-ui.html",extra_context={"schema_url": "openapi-schema"},),name="swagger-ui",),
    path('courses-schema/', get_schema_view(title="Courses Api",description="Api for the courses"), name='openapi-schema'),
    path('our-blog/', blog, name='blog'),
]

handler404 = 'authentication.views.page_404'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

# python manage.py collectstatic (after add first 2 line in url then run this command)

home/urls.py
from django.urls import path
from .views import *

# add api url
from rest_framework import routers

router = routers.DefaultRouter()
from rest_framework import routers

router = routers.DefaultRouter()



urlpatterns = [
    path('edit/coursese/<int:id>/', EditCourses, name='edit-courses'),
    path('delete/courses/<int:id>/', DeleteCourses, name='delete-courses'),
    path('class/', Videoclass, name='classes'),
    path('student-data/', studentData, name='user-data'),
    path('student-data/delete/<int:id>/', DeleteStudent, name='delete-student'),
    path('video-api/', VideoApi.as_view(), name='video'),
    path('subject-api/', SubjectApiView, name='subject_api'),
    path('student-query-api/', StudentqueryView, name='student_query'),
    path('contact-api/', ContactView),
    path('delete-class/<int:id>/', deletevideo, name='delete-class'),
    path('edit/class-video/<int:id>/', Editclass, name='editvideo'),
    path('<slug:slug>/', get_cours, name='getcourses'),
    path('edit-blog/<int:id>/', editblog, name='edit-blog'),
]

home/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone

# import userforeignkey
from django_userforeignkey.models.fields import UserForeignKey

# import slugify 
from django.utils.text import slugify

class Trackable(models.Model):
    creted_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created_by = UserForeignKey(related_name='created_%(class)s' ,auto_user_add=True, on_delete=models.CASCADE, blank=True, null=True)
    updated_by = UserForeignKey(related_name='modified_%(class)s' ,auto_user=True, blank=True, null=True )

    def __str__(self):
        return self.created_by

    # class Meta:
    #     abstract =True


# Create your models here.

class Subject(models.Model):
    created_by = UserForeignKey(related_name='created_%(class)s' ,auto_user_add=True, on_delete=models.CASCADE, blank=True, null=True)
    subject_name = models.CharField(max_length=100 ,null=True, blank=True)
    subject_code = models.CharField(max_length=100 ,null=True, blank=True)

    def __str__(self):
        return self.subject_name


class courses(models.Model):
    subjectname =  models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    notes = models.FileField(upload_to="notes/", null=True, blank=True, default=None)
    paid = models.BooleanField(null=True, blank=True, default=False)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(courses, self).save(*args, **kwargs)

    def __str__(self):
        return self.title    

    class Meta:
        ordering = ['subjectname']


class StudentQuery(models.Model):
    query = models.CharField(max_length=500, null=True, blank=True)
    solution = models.CharField(max_length=500, null=True, blank=True)


class Contact(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    number = models.CharField(max_length=100 , null=True, blank=True)  

class Notification(models.Model):
    notification = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)


class BlogStory(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    story = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    story_pic = models.ImageField(upload_to="storypic/", null=True, blank=True)
    upload_date = models.DateField(default=timezone.now)


class classes(models.Model):
    courses = models.ForeignKey(Subject, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="videothumb/", null=True, blank=True, default=None)
    upload_date = models.DateTimeField(default=timezone.now)
    video = models.FileField(upload_to="classvideo/", null=True, blank=True ,validators=[FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'webm', 'avi', 'mkv'])])
    title = models.CharField(max_length=200, null=True, blank=True)    
    
    # def __str__(self):
    #     return self.courses.subjectname   

templates/index/footer.html
<div>
    <div class="bg-dark h-100 w-100">
        <div class="py-3 px-2">
            <div class="row text-light justify-content-between w-100">
                <div class="col"><h4 class="ff">
                    Follow our page on
                </h4>
            <hr style="color: red; width: 50%;"></div>
                <div class="col">
                    <!-- <h4 class="ff text-end">Contact Form </h4> -->
                </div>

            </div>
            <div class="py-4">
                <div class="row w-100">
                    <div class="col ff">
                          <div class="px-1">
                            <div>
                                <p class="text-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ipsum modi </p>
                            </div>
                            <hr style="color: #ddd; width: 90%; margin: auto;">
                            <div>
                                <p class="ff text-light pt-2">
                                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque maiores, delectus repellat porro veritatis sit, ullam optio in pariatur corporis expedita corrupti quia eos nihil aperiam aut sed exercitationem consequatur.
                                </p>
                            </div>
                          </div>
                    </div>
                    <div class="col">
                        <p class="text-light">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos, quis perferendis quam ullam dolore et laboriosam, laudantium similique aspernatur dolor iure saepe repudiandae sed explicabo assumenda incidunt velit, id fuga.</p>
                        <div>
                            <div class="d-flex">
                                <div>
                                    <a href="" class="social-link">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook text-light py-2 px-2" viewBox="0 0 16 16">
                                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                                          </svg>
                                    </a>
                                </div>
                                <div>
                                    <a href="" class="insta">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram text-light py-2 px-2" viewBox="0 0 16 16">
                                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                                          </svg>
                                    </a>
                                </div>
                                <div>
                                    <a href="" class="social-link">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter text-light py-2 px-2" viewBox="0 0 16 16">
                                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334q.002-.211-.006-.422A6.7 6.7 0 0 0 16 3.542a6.7 6.7 0 0 1-1.889.518 3.3 3.3 0 0 0 1.447-1.817 6.5 6.5 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.32 9.32 0 0 1-6.767-3.429 3.29 3.29 0 0 0 1.018 4.382A3.3 3.3 0 0 1 .64 6.575v.045a3.29 3.29 0 0 0 2.632 3.218 3.2 3.2 0 0 1-.865.115 3 3 0 0 1-.614-.057 3.28 3.28 0 0 0 3.067 2.277A6.6 6.6 0 0 1 .78 13.58a6 6 0 0 1-.78-.045A9.34 9.34 0 0 0 5.026 15"/>
                                          </svg>
                                    </a>
                                </div>
                                <div>
                                    <a href="" class="social-link">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube text-light px-2 py-2" viewBox="0 0 16 16">
                                            <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.01 2.01 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.01 2.01 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31 31 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.01 2.01 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A100 100 0 0 1 7.858 2zM6.4 5.209v4.818l4.157-2.408z"/>
                                          </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>  
                    <div class="col">
                        <div>
                            <div>
                                <form action="" class="py-1 ff px-3" method="post">
                                    {% csrf_token %}
                
                                    <div class="input-data">
                                        <input type="text" name="name" id="">
                                        <div class="underline"></div>
                                        <label for="">Name</label>
                                    </div>
                                    
                
                                    <div class="input-data my-4">
                                        <input type="number" name="phone_number" id="" >
                                        <div class="underline"></div>
                                        <label for="">Phone Number</label>
                                    </div>
                
                                    <div>
                                        <button type="submit" class="btn btn-primary w-100 text-light py-2">Submit</button>
                                    </div>
                
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/index/header.html
<div>
  <div>
    <div>
      <div class="header position-relative m-auto">
        <div class="m-auto navbar">
          <div class="d-flex justify-content-between m-auto " style="width: 98%;">
            <div>
              <div class="px-1 py-1 menu-bar" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><img class="navbar-logo"
                  src="/static/images/images.png" alt=""></div>


            </div>
            <div>

            </div>
            <div class="d-flex justify-content-between">
              {% if request.user.is_authenticated %}
              <div class="mx-2 py-1">
                <button type="button" class="btn btn-sm  position-relative notification-btn" data-bs-toggle="offcanvas"
                  data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                  <span class="material-symbols-outlined text-light" style="width: 10px; height: 17px;">
                    notifications_active
                  </span>
                  <span
                    class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                    <span class="visually-hidden">New alerts</span>
                  </span>
                </button>
              </div>
              <a href="/register/logout/" class="btn btn-sm sign-btn mx-2 ff">Logout</a>
              {% else %}
              <a href="/register/login/" class="btn btn-sm login-btn mx-2 ff">Login</a>
              <a href="/register/sign-up/" class="btn btn-sm sign-btn mx-2 ff">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- side bar model -->
<div class="offcanvas offcanvas-start side-bar" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1"
  id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">VMEC</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="">
    <div class="container-fluid">
      <div class="class=" collapse navbar-collapse" id="navbarSupportedContent"">
        <div class="">
          <ul class=" navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
        <li class="nav-item d-flex px-2">
          <span class="material-symbols-outlined span-icon text-light mt-2">
            home
          </span>
          <a class="nav-link px-2 ff" href="/">Home</a>
        </li>
        </ul>
        <ul class="navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
          <li class="nav-item d-flex px-2">
            <span class="material-symbols-outlined mt-2">
              man
            </span>
            <a class="nav-link px-2 ff" href="/about/">About</a>
          </li>
        </ul>
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
          <li class="nav-item d-flex px-2">
            <span class="material-symbols-outlined mt-2">
              person
            </span>
            <a class="nav-link px-2 ff" href="/edit-profile/{{request.user.id}}/">Profile</a>
          </li>
        </ul>
        {% endif %}
        <ul class="navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
          <li class="nav-item d-flex px-2">
            <span class="material-symbols-outlined mt-2">
              menu_book
            </span>
            <a class="nav-link px-2 ff" href="/courses/">Courses</a>
          </li>
        </ul>
        <ul class="navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
          <li class="nav-item dropdown d-flex px-2">
            <span class="material-symbols-outlined mt-2 ">
              video_library
            </span>
            <a class="nav-link px-2 ff" href="/our-courses/class/">
              Classes
            </a>
          </li>
        </ul>
        {% if request.user.is_superuser %}
        <ul class="navbar-nav me-auto mb-2 my-1 mb-lg-0 active">
          <li class="nav-item dropdown d-flex px-2">
            <span>
              <span class="material-symbols-outlined mt-2">
                dataset
              </span>
            </span>
            <a class="nav-link dropdown-toggle px-2" href="#" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Web Data
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/our-courses/student-data/">Student Data</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
            </ul>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</div>
</div>
</div>

<div class="chat-menu">
  <div class="d-flex justify-content-end ">
    <div class="chat-section">
      <div>
        <span class="text-light material-symbols-outlined" style="padding: 10px;">
          forum
        </span>
      </div>
    </div>
  </div>
</div>

<!-- notification bar  -->
<div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel"
  style="width: 350px !important;">
  <div class="offcanvas-header">
    <div class="d-flex">
      <h5 class="offcanvas-title" id="offcanvasRightLabel">Notification</h5>
      {% if perms.home.add_notification %}
      <a href="{% url "notify" %}" class="bg-primary note-btn mx-2"><span class="material-symbols-outlined text-light pt-1">
          add
        </span></a>
      {% endif %}  
    </div>

    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <hr>
  <div class="offcanvas-body" style="width: 375px !important;">
    {% for item in note %}
    <div class="d-flex">
      <div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel"
        style="width: 350px !important;">
        <div class="offcanvas-header">
          <div class="d-flex">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Notification</h5>
            <a href="{% url "notify" %}" class="bg-primary note-btn mx-2"><span class="material-symbols-outlined text-light pt-1">
                add
              </span></a>
          </div>

          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <hr>
        <div class="offcanvas-body" style="width: 375px !important;">
          {% comment %} {% for item in note %}
          <div class="d-flex">

            <div class="alert alert-info" role="alert" style="width:-webkit-fill-available;">
              <p class="nt-btn">{{item.notification}}</p>
              <p class="video-upload-date text-end">{{item.date}}</p>
            </div>
            <div style="height: fit-content;">
              <span class="material-symbols-outlined text-light video-action-btn bg-primary mx-1 my-1 cr">
                edit
              </span>
              <span class="material-symbols-outlined text-light video-action-btn bg-danger mx-1 my-1 cr">
                delete
              </span>
            </div>


          </div>
          {% endfor %} {% endcomment %}

        </div>
      </div>
      <div class="alert alert-info" role="alert" style="width:-webkit-fill-available;">
        <p class="nt-btn">{{item.notification}}</p>
        <p class="video-upload-date text-end">{{item.date}}</p>
      </div>

    </div>
    {% endfor %}

  </div>
</div>