english_grammar/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from home.views import home
from authentication.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
# api schema
from rest_framework.schemas import get_schema_view
# swagger 
from rest_framework_swagger.views import get_swagger_view
# from django.conf.urls import url

# errr handle pages
from authentication.views import page_404
from django.views.static import serve
from home.views import blog




urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('register/', include('authentication.urls')),
    path('', home),
    path('about/', about, name='about'),
    path('edit-profile/<int:id>/', profile_edit, name='profile-edit'),
    path('courses/', Courses, name='courses'),
    path('our-courses/', include('home.urls')),
    path('captcha/', include('captcha.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger-ui/',TemplateView.as_view(template_name="templates/home/swagger-ui.html",extra_context={"schema_url": "openapi-schema"},),name="swagger-ui",),
    path('courses-schema/', get_schema_view(title="Courses Api",description="Api for the courses"), name='openapi-schema'),
    path('our-blog/', blog, name='blog'),
]

handler404 = 'authentication.views.page_404'

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

# python manage.py collectstatic (after add first 2 line in url then run this command)

home/urls.py
from django.urls import path
from .views import *

# add api url
from rest_framework import routers

router = routers.DefaultRouter()
from rest_framework import routers

router = routers.DefaultRouter()



urlpatterns = [
    path('edit/coursese/<int:id>/', EditCourses, name='edit-courses'),
    path('delete/courses/<int:id>/', DeleteCourses, name='delete-courses'),
    path('class/', Videoclass, name='classes'),
    path('student-data/', studentData, name='user-data'),
    path('student-data/delete/<int:id>/', DeleteStudent, name='delete-student'),
    path('video-api/', VideoApi.as_view(), name='video'),
    path('subject-api/', SubjectApiView, name='subject_api'),
    path('student-query-api/', StudentqueryView, name='student_query'),
    path('contact-api/', ContactView),
    path('delete-class/<int:id>/', deletevideo, name='delete-class'),
    path('edit/class-video/<int:id>/', Editclass, name='editvideo'),
    path('<slug:slug>/', get_cours, name='getcourses'),
    path('edit-blog/<int:id>/', editblog, name='edit-blog'),
]

home/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone

# import userforeignkey
from django_userforeignkey.models.fields import UserForeignKey

# import slugify 
from django.utils.text import slugify

class Trackable(models.Model):
    creted_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created_by = UserForeignKey(related_name='created_%(class)s' ,auto_user_add=True, on_delete=models.CASCADE, blank=True, null=True)
    updated_by = UserForeignKey(related_name='modified_%(class)s' ,auto_user=True, blank=True, null=True )

    def __str__(self):
        return self.created_by

    # class Meta:
    #     abstract =True


# Create your models here.

class Subject(models.Model):
    created_by = UserForeignKey(related_name='created_%(class)s' ,auto_user_add=True, on_delete=models.CASCADE, blank=True, null=True)
    subject_name = models.CharField(max_length=100 ,null=True, blank=True)
    subject_code = models.CharField(max_length=100 ,null=True, blank=True)

    def __str__(self):
        return self.subject_name


class courses(models.Model):
    subjectname =  models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    notes = models.FileField(upload_to="notes/", null=True, blank=True, default=None)
    paid = models.BooleanField(null=True, blank=True, default=False)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(courses, self).save(*args, **kwargs)

    def __str__(self):
        return self.title    

    class Meta:
        ordering = ['subjectname']


class StudentQuery(models.Model):
    query = models.CharField(max_length=500, null=True, blank=True)
    solution = models.CharField(max_length=500, null=True, blank=True)


class Contact(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    number = models.CharField(max_length=100 , null=True, blank=True)  

class Notification(models.Model):
    notification = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)


class BlogStory(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    story = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    story_pic = models.ImageField(upload_to="storypic/", null=True, blank=True)
    upload_date = models.DateField(default=timezone.now)


class classes(models.Model):
    courses = models.ForeignKey(Subject, on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to="videothumb/", null=True, blank=True, default=None)
    upload_date = models.DateTimeField(default=timezone.now)
    video = models.FileField(upload_to="classvideo/", null=True, blank=True ,validators=[FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'webm', 'avi', 'mkv'])])
    title = models.CharField(max_length=200, null=True, blank=True)    
    
    # def __str__(self):
    #     return self.courses.subjectname   

home/forms.py
from django import forms
from .models import BlogStory


class Blogform(forms.ModelForm):
    class Meta:
        model = BlogStory
        fields = ['title', 'story', 'description', 'story_pic']

home/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required,permission_required

# models
from home.models import *
from .forms import Blogform

# login required
from django.contrib.auth.decorators import login_required
from authentication.views import login

# api 
from rest_framework.views import APIView
from .serializers import *
from rest_framework.response import Response
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view

# messages
from django.contrib import messages


# Create your views here.
def home(request):
    course= courses.objects.all().order_by('-id')[:4]
    story = BlogStory.objects.all().order_by('-id')[:4]
    sutdent_query = StudentQuery.objects.all().order_by('-id')[:4]
    notification = Notification.objects.all().order_by('-id')[:4]
    content = {
        'courses':course,
        'story': story,
        'query':sutdent_query,
        'note':notification
    }
    if request.method == 'POST':
       query = request.POST.get('student_query')
       sutdent_query = StudentQuery.objects.create(query=query)
       messages.success(request, "Student Query Submitted")
       return redirect('/')
    return render(request, "home/dashboard.html", content)

def EditCourses(request, id):
    subject = Subject.objects.all()
    cours =courses.objects.get(id=id)
    context = {
        'data':cours,
        'subject':subject,
        'note' : Notification.objects.all().order_by('-id')[:4]
    }

    if request.method == 'POST':
        new_subject = request.POST.get('subject')
        subject = Subject.objects.get(id=new_subject)
        title = request.POST.get('title')
        description = request.POST.get('description')
        notes = request.FILES.get('notes')
        paid= request.POST.get('paid')
        if notes is not None:
            cours.notes = notes
            cours.subjectname = subject
            cours.description = description
            cours.save()
            return redirect('/courses/')
        cours.subjectname = subject
        cours.description = description
        cours.title = title
        cours.paid = paid
        cours.save()
        messages.success(request, "Course Was Updated")
        return redirect('/courses/')
    messages.error(request, "course is not Updated.Try again")
    return render(request, 'home/edit_courses.html' , context)

def DeleteCourses(request, id):
    object = courses.objects.get(id=id)
    object.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('/courses/')

@login_required
def Videoclass(request):
    video = classes.objects.all().order_by('-id')
    course = Subject.objects.all().order_by('-id')
    searchvideo = request.GET.get('search-video')
    content = {
        'data':video,
        'object' : course,
        'note' : Notification.objects.all().order_by('-id')[:4]
    }
    if searchvideo:
        print(searchvideo)
        video = classes.objects.all().filter(title__icontains=searchvideo)  
        content = {
            'data':video
        }
        return render(request, 'home/classes.html', content)      

    if request.method == 'POST':
        subject  = request.POST.get('courses')
        course = Subject.objects.get(id=subject)
        video = request.FILES['video']
        title = request.POST.get('title')
        thumbnail = request.FILES['thumbnail']
        data = classes(courses=course, video=video, title=title, thumbnail=thumbnail)
        data.save()
        return redirect('classes')
    return render(request, 'home/classes.html', content)

def Editclass(request, id):
    data = classes.objects.get(id=id)
    cours = courses.objects.all()
    context = {
        'object':data,
        'courses':cours,
        'note' : Notification.objects.all().order_by('-id')[:4]
    }
    if request.method == 'POST':
        video_cours = request.POST.get('cours')
        thumb = request.FILES.get('thumbnail')
        video = request.FILES.get('video')
        title = request.POST.get('title')
        video_courses = Subject.objects.get(id=video_cours)
        data.courses = video_courses
        data.thumbnail = thumb
        data.video = video
        data.title = title
        data.save()
        messages.success(request, "Video Successfully Updated")
        return redirect('classes')
    messages.error(request, "Video Is Not Updated")
    return render(request, 'home/edit_video_class.html', context)

def studentData(request):
    student = User.objects.all().order_by('-id')
    user = request.user.groups.all()
    print(user)
    context = {
        'data': student,
        'groups' : Group.objects.all(),
        'user_droup' : user,
        'note' : Notification.objects.all().order_by('-id')[:4]
    }       
          
    return render(request, 'home/student-data.html', context)

def DeleteStudent(reuqest,id):
    student = User.objects.get(id=id)
    student.delete()
    messages.success(reuqest, "Student Data Successfully Delete")
    return redirect('/our-courses/student-data/')
    
def deletevideo(request, id):
    cours = classes.objects.get(id=id)
    cours.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('classes')

def get_cours(request, slug):
    if slug:
        data = courses.objects.get(slug=slug)
        note = Notification.objects.all().order_by('-id')[:4]
        context = {
            'item': data,
            'note' : note
        }
        return render(request, 'home/cours.html', context)

# classed based api
class VideoApi(APIView):

    def get(self, request):
        video_class = classes.objects.all()
        serializers = VideoSerializers(video_class, many=True)
        return Response(serializers.data, status.HTTP_200_OK)
     
# function based api of Subject model
@csrf_exempt
def SubjectApiView(request):
    query_set = Subject.objects.all()
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = SubjectSerializers(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)
    
    serilizer = SubjectSerializers(query_set, many=True)
    return JsonResponse(serilizer.data, safe=False)  

@api_view(['GET','POST'])
def StudentqueryView(request):
    query_set = StudentQuery.objects.all()
    try:
        if request.method == 'GET':
            serializer = StudentquerySerializers(query_set, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.data)

    except:
        if request.method == 'POST':
            serializer = StudentquerySerializers(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','POST'])
def ContactView(request):
    query_set = Contact.objects.all()
    try:
        if request.method == 'GET':
            serializer = ContactSerializers(query_set, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.data)
    except:
        if request.method == 'POST':
            serializer = ContactSerializers(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
           
@login_required
def blog(request):
    item = BlogStory.objects.all().order_by('-id')
    note = Notification.objects.all().order_by('-id')[:4]
    context = {
        'blog':item,
        'note':note
    }
    
    if request.method == 'POST':
        form = Blogform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Blog Created")
            return redirect('blog')    
    return render(request, 'home/blog.html', context)

def editblog(request, id):
    item = BlogStory.objects.get(id=id)
    note = Notification.objects.all().order_by('-id')[:4]
    context = {
        'blog':item,
        'note':note
    }
    if request.method == 'POST':
        form = Blogform(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            messages.success(request, "Blog Updated Successfully")
            return redirect('blog')
    messages.error(request, "Blog Is Not Updated Try Again")    
    return render(request, 'home/edit-blog.html', context)

english_grammar/templates/home/classes.html
{% extends "layout/base.html" %}

{% block title %}VMEC - Class {% endblock title %}

{% block stylesheet %}

<style>
.underline::before{
 position: relative;
}

.toast {
  color: #fff;
  position: fixed;
  top: 20px;
  right: -300px; /* start off-screen */
  min-width: 250px;
  padding: 15px;
  border: 1px solid transparent;
  border-radius: 4px;
  z-index: 1000;
  transition: right 0.5s ease-in-out;
  margin-top: 45px;
}
.toast-show {
  right: 20px; /* move on-screen */
}

.toast-hide {
  right: -300px; /* move off-screen */
}

.toast:not(.show){
  display: block !important;
}
</style>

{% endblock stylesheet %}

{% block content %}

{% if messages %}
    
        {% for message in messages %}
            <div class="bg-{{ message.tags }} toast ff">
                {{ message }}
            </div> 
        {% endfor %}
    
{% endif %}

<div>
    <div>
        <div class="m-auto" style="width: 85%;">
            <div class="py-5 ">
                <div class="row">
                      <div class="col-md-7 col-md-7 class-header col-sm-12 my-1">
                        <h4 class="ff">Our Classes</h4>
                      </div>
                      
                      <div class="col-md-5 col-md-5 pl-2 col-sm-12 my-1 search-upload-bar text-end" style="padding-right: 40px;">
                        <div class="row">
                          <div class="col-md-8 col-sm-12 my-1">
                            <form action="" class="search-video d-flex justify-content-between" method="get">
                              <div class="input-data ff">
                                <input type="text" name="search-video" id="" required>
                                <div class="underline"></div>
                                <label for="">Search Video</label>
                              </div>
                              <div class="mx-1">
                                  <input type="submit" class="btn btn-sm btn-primary">
                              </div>
                            </form>
                          </div>
                          {% comment %} <pre>{{perms.home.view_classes}}</pre> {% endcomment %}
                          {% if perms.home.add_classes %}
                            <div class="col-md-4 col-sm-12 my-1" style="padding-right: 35px;">
                              <button class="btn btn-sm btn-success text-light ff" data-bs-toggle="modal" data-bs-target="#exampleModal">Upload</button>
                            </div> 
                          {% endif %}
                        </div>
                      </div>
                     
                      
                      
                </div>
                <div class="py-3">
                    <div class="container-box">
                        {% for item in data %}
                            <div class="item">
                                <div class="video-box">
                                    <video controls controlsList="nodownload" poster="/media/{{item.thumbnail}}" class="class-video" style="border-radius: 2px;" id="myVideo">
                                        <source src="/media/{{item.video}}" type="video/mp4">
                                    </video>
                                </div>
                                <div>
                                  <p class="pt-2 video-title">{{item.title |slice:"0:200"}}</p>
                                  <div class="action d-flex justify-content-end">
                                    {% if perms.home.change_classes %}
                                      <a href="/our-courses/edit/class-video/{{item.id}}/" class="btn btn-sm cr"><span class="material-symbols-outlined text-light bg-primary video-action-btn">
                                        edit
                                        </span></a>
                                    {% endif %}  
                                    {% if perms.home.delete_classes %}
                                      <form action="/our-courses/delete-class/{{item.id}}/" method="get">
                                        <button type="submit" class="btn btn-sm cr"><span class="material-symbols-outlined text-light bg-danger video-action-btn">
                                          delete
                                          </span></button>
                                      </form>
                                    {% endif %}
                                  </div>
                                  <p class="text-end video-upload-date">{{item.upload_date}}</p>
                                </div>
                            </div>
                        {% empty %}    
                          No Video Found 
                        {% endfor %}
            
                    </div> 
                    
                </div>
            </div>
        </div>
    </div>
</div>




<!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button> -->
  
<!-- upload video -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Upload Video</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div>
            <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="my-4">
                    <label for="" class="form-label ff">Select Course</label>
                    <select class="form-control ff" name="courses" id="">
                        <option value="">-----</option>
                        {% for item in object %}
                          <option value="{{item.id}}">{{item.subject_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="my-4">
                    <label for="" class="form-label ff">Uplaod Video</label>
                    <input type="file" class="form-control" name="video" accept="video" id="" required>
                    <div class="underline"></div>                    
                </div>
                <div class="my-4">
                  <label for="" class="form-label ff">Uplaod Thumbnail</label>
                  <input type="file" class="form-control" name="thumbnail" id="" required>
                  <div class="underline"></div>                    
              </div>
                <div class="input-data my-4 ff">
                    <input type="text" name="title" id="" required>
                    <div class="underline"></div>
                    <label for="">Title</label>
                </div>
                <div>
                    <button type="submit" class="btn btn-success w-100 ff">Upload Video</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<script>
  document.addEventListener('DOMContentLoaded', function() {
     var toasts = document.querySelectorAll('.toast');
     toasts.forEach(function(toast) {
         setTimeout(function() {
             toast.classList.add('toast-show');
         }, 100); // slight delay to trigger the animation

         setTimeout(function() {
             toast.classList.remove('toast-show');
             toast.classList.add('toast-hide');
         }, 10000); // hide after 10 seconds
     });
 }); 
</script>

{% block externaljs %}{% endblock externaljs %}

english_grammar/templates/home/profile_page.html
{% extends "layout/base.html" %}

{% block title %}VMEC - Profile {% endblock title %}

{% block stylesheet %}

<style>
    .toast {
        color: #fff;
        position: fixed;
        top: 20px;
        right: -300px; /* start off-screen */
        min-width: 250px;
        padding: 15px;
        border: 1px solid transparent;
        border-radius: 4px;
        z-index: 1000;
        transition: right 0.5s ease-in-out;
        margin-top: 45px;
    }
    .toast-show {
        right: 20px; /* move on-screen */
    }
    
    .toast-hide {
        right: -380px; /* move off-screen */
    }
    
    .toast:not(.show){
        display: block !important;
    }

</style>

{% endblock stylesheet %}

{% block content %}


{% if messages %}
    
        {% for message in messages %}
            <div class="bg-{{ message.tags }} toast ff">
                {{ message }}
            </div> 
        {% endfor %}
    
{% endif %}

<div>
    <div class="w-100">
        <div class="m-auto" style="width:65%">
            <div class="py-5">
                <div class="profile-heading-box mx-3">
                    <div class="m-auto py-1 " style="width: 40%;">
                        <div class="">
                             <h4 class="text-center text-light">Update Your Pofile</h4> 
                        </div>
                    </div>
                </div>
               
                <div class="profile-update">
                    <form action="" class="py-4 ff px-3" method="post">
                        {% csrf_token %}
    
                        <div class="input-data my-4">
                            <input type="text" name="name" value="{{data.username}}" id="" required>
                            <div class="underline"></div>
                            <label for=""></label>
                        </div>
    
                        <div class="input-data my-4">
                            <input type="email" name="email" value="{{data.email}}" id="" required>
                            <div class="underline"></div>
                            <label for=""></label>
                        </div>
                        
                        <div class="input-data my-4">
                            <input type="number" name="number" value="{{data.first_name}}" id="" required>
                            <div class="underline"></div>
                            <label for=""></label>
                        </div>

                        
                        <div class="row">
                            <div class="col-md-6 my-1 col-sm-12 col-lg-6">
                                <a href="/" class="btn btn-sm text-light py-1 mx-1 my-1" style="background-color: #737373;">Back</a>
                                <button type="submit" class="btn btn-sm btn-primary text-light py-1 mx-2 my-1">Update</button>
                            </div>
                            <div class="col-md-6 my-1 col-sm-12 col-lg-6 text-end">
                                <a href="/register/change-password/" class="btn btn-sm btn-warning">Change Password</a>
                            </div>
                        </div>
                        
    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>








{% endblock content %}

{% block externaljs %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
       var toasts = document.querySelectorAll('.toast');
       toasts.forEach(function(toast) {
           setTimeout(function() {
               toast.classList.add('toast-show');
           }, 100); // slight delay to trigger the animation

           setTimeout(function() {
               toast.classList.remove('toast-show');
               toast.classList.add('toast-hide');
           }, 10000); // hide after 10 seconds
       });
   }); 
</script>

{% endblock externaljs %}